### ISSUE TITLE
Heroku app is down

### ISSUE THREAD

**Issue by rivermont** [Pezmc/BibLaTeX-Linter#13]
The published web app [biblatex-linter.herokuapp.com](https://biblatex-linter.herokuapp.com) displays an application error.

**Comment by marcoruizrueda** [comment]
The web based version of this checker is NOT available: https://biblatex-linter.herokuapp.com/

Could you @Pezmc  please update it?

Thanks for the repo.

**Comment by Pezmc** [comment]
Unfortunately Heroku have stopped supporting free dynos and I don’t have the resources to pay for the linter to be hosted. Do either of you know of any free hosting for open source project equivalents we could use?

**Comment by Pezmc** [comment]
@rivermont @marcoruizrueda I've migrated to River, https://biblatex-linter.onrender.com
